include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    # pedantic: enabled
    prefer_single_quotes: true
    prefer_adjacent_string_concatenation: true

    # effective_dart: enabled
    avoid_catches_without_on_clauses: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_returning_null: true
    avoid_returning_this: true
    lines_longer_than_80_chars: true

    # Contradictory to `prefer_adjacent_string_concatenation`
    no_adjacent_strings_in_list: false

    # Project rules
    always_use_package_imports: true
